import type { MeasurementItem, MeasurementRecord } from './types';

export const initialItems: MeasurementItem[] = [
    { id: '1', name: '50m 달리기', unit: '초', recordType: 'time', isPaps: true, category: 'PAPS', videoUrl: 'https://www.youtube.com/watch?v=Gk3_Z8v1WqA' },
    { id: '2', name: '윗몸 말아올리기', unit: '회', recordType: 'count', isPaps: true, category: 'PAPS', videoUrl: 'https://www.youtube.com/watch?v=n5LwW0Q3B_c' },
    { id: '3', name: '왕복오래달리기', unit: '회', recordType: 'count', isPaps: true, category: 'PAPS', videoUrl: 'https://www.youtube.com/watch?v=kY1w6m3Q_L0' },
    { id: '4', name: '제자리 멀리뛰기', unit: 'cm', recordType: 'distance', isPaps: true, category: 'PAPS', videoUrl: 'https://www.youtube.com/watch?v=A3_k9L1yI00' },
    { id: '5', name: '앉아윗몸앞으로굽히기', unit: 'cm', recordType: 'distance', isPaps: true, category: 'PAPS', videoUrl: 'https://www.youtube.com/watch?v=w9_t2H8b_aU' },
    { id: 'bmi', name: '체질량지수(BMI)', unit: 'kg/m²', recordType: 'compound', isPaps: true, isCompound: true, category: 'PAPS', videoUrl: 'https://www.youtube.com/watch?v=n_Q3_Z8v1W0' },
    { id: 'b-shot', name: '슛', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '농구' },
    { id: 'b-assist', name: '어시스트', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '농구' },
    { id: 'b-rebound', name: '리바운드', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '농구' },
    { id: 'b-steal', name: '스틸', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '농구' },
    { id: 'v-spike', name: '스파이크', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '배구' },
    { id: 'v-receive', name: '리시브', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '배구' },
    { id: 'v-toss', name: '토스', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '배구' },
    { id: 'v-serve', name: '서브', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '배구' },
    { id: 'bs-batting', name: '타격', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '야구' },
    { id: 'bs-baserunning', name: '주루', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '야구' },
    { id: 'bs-throwing', name: '송구', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '야구' },
    { id: 'bs-catching', name: '포구', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '야구' },
    { id: 's-goal', name: '득점', unit: '점', recordType: 'count', isPaps: false, goal: 5, category: '축구' },
    { id: 's-pass', name: '패스', unit: '점', recordType: 'count', isPaps: false, goal: 20, category: '축구' },
    { id: 's-dribble', name: '돌파성공', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '축구' },
    { id: 's-defense', name: '수비성공', unit: '점', recordType: 'count', isPaps: false, goal: 15, category: '축구' },
    { id: 'd-attack', name: '공격성공', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '피구' },
    { id: 'd-pass', name: '패스성공', unit: '점', recordType: 'count', isPaps: false, goal: 20, category: '피구' },
    { id: 'd-catch', name: '포구', unit: '점', recordType: 'count', isPaps: false, goal: 10, category: '피구' },
    { id: 'd-dodge', name: '회피성공', unit: '점', recordType: 'count', isPaps: false, goal: 15, category: '피구' },
];
